// 引用：https://github.com/vuejs/create-vue/blob/main/utils/banners.ts
const defaultBanner = 'Wetpl -  A Scaffold for Quickly Creating Project';

// generated by the following code:
//
// require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('Wetpl -  A Scaffold for Quickly Creating Project'))
//
// Use the output directly here to keep the bundle small.
const gradientBanner =
    '\u001b[38;2;66;211;146mW\u001b[39m\u001b[38;2;66;211;146me\u001b[39m\u001b[38;2;66;211;146mt\u001b[39m\u001b[38;2;66;211;146mp\u001b[39m\u001b[38;2;66;211;146ml\u001b[39m \u001b[38;2;67;209;149m-\u001b[39m  \u001b[38;2;68;206;152mA\u001b[39m \u001b[38;2;69;204;155mS\u001b[39m\u001b[38;2;70;201;158mc\u001b[39m\u001b[38;2;71;199;162ma\u001b[39m\u001b[38;2;72;196;165mf\u001b[39m\u001b[38;2;73;194;168mf\u001b[39m\u001b[38;2;74;192;171mo\u001b[39m\u001b[38;2;75;189;174ml\u001b[39m\u001b[38;2;76;187;177md\u001b[39m \u001b[38;2;77;184;180mf\u001b[39m\u001b[38;2;78;182;183mo\u001b[39m\u001b[38;2;79;179;186mr\u001b[39m \u001b[38;2;80;177;190mQ\u001b[39m\u001b[38;2;81;175;193mu\u001b[39m\u001b[38;2;82;172;196mi\u001b[39m\u001b[38;2;83;170;199mc\u001b[39m\u001b[38;2;83;167;202mk\u001b[39m\u001b[38;2;84;165;205ml\u001b[39m\u001b[38;2;85;162;208my\u001b[39m \u001b[38;2;86;160;211mC\u001b[39m\u001b[38;2;87;158;215mr\u001b[39m\u001b[38;2;88;155;218me\u001b[39m\u001b[38;2;89;153;221ma\u001b[39m\u001b[38;2;90;150;224mt\u001b[39m\u001b[38;2;91;148;227mi\u001b[39m\u001b[38;2;92;145;230mn\u001b[39m\u001b[38;2;93;143;233mg\u001b[39m \u001b[38;2;94;141;236mP\u001b[39m\u001b[38;2;95;138;239mr\u001b[39m\u001b[38;2;96;136;243mo\u001b[39m\u001b[38;2;97;133;246mj\u001b[39m\u001b[38;2;98;131;249me\u001b[39m\u001b[38;2;99;128;252mc\u001b[39m\u001b[38;2;100;126;255mt\u001b[39m';

const getBanner = () => {
    const bannerTxt = process.stdout.isTTY && process.stdout.getColorDepth() > 8 ? gradientBanner : defaultBanner;
    return `\n${bannerTxt}\n`;
};

export default getBanner;
